const apiFuction = (req,res) => {
    let details = [
        {
            id: 1,
            name: "Jollof Rice",
            rating: "1,500",
            price: 3500,
            description: "A popular one-pot dish made with rice, tomatoes, peppers, and various spices. It's known for its rich, flavorful taste.",
            image: "https://grandbaby-cakes.com/wp-content/uploads/2023/04/jollof-rice-recipe-23.jpg",
            tag: "rice",
        },
        {
            id: 2,
            name: "Egusi Soup",
            rating: "2,000",
            price: 1400,
            description: "A thick, hearty soup made from ground melon seeds, vegetables, and meat or fish. It's often served with fufu.",
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTICPxWE33oyjEAaa4WeQefZ5vXVtEC_AOsrA&usqp=CAU",
            tag: "soup",
        },
        {
            id: 3,
            name: "Suya",
            rating: "800",
            price: 1000,
            description: "Skewered and grilled meat, typically beef or chicken, seasoned with a spicy peanut sauce",
            image: "https://nkechiajaeroh.com/wp-content/uploads/2020/06/Main-photo-4-Nigerian-Chicken-Suya.jpg",
            tag: "Protein",
        },
        {
            id: 4,
            name: "Pounded Yam and Egusi Soup",
            rating: "3.50",
            price: 5500,
            description: "Pounded yam served with a thick soup made from melon seeds, leafy vegetables, and protein",
            image: "https://www.goodmealtime.com/wp-content/uploads/2023/02/Pounded-Yam.jpg",
            tag: "swallow",
        },
        {
            id: 5,
            name: "Akara",
            rating: "2.50",
            price: 1200,
            description: "Deep-fried bean cakes made from black-eyed peas and spices, often served as a snack or breakfast.",
            image: "https://nkechiajaeroh.com/wp-content/uploads/2020/01/Akara-recipe-main-photo-2.jpg",
            tag: "snack",
        },
        {
            id: 6,
            name: "Moi Moi",
            rating: "1.20",
            price: 1500,
            description: "A steamed bean pudding made from grounded peeled beans, peppers, and spices.",
            image: "https://tribuneonlineng.com/wp-content/uploads/2020/01/MoiMoi.jpg"
        },
        {
            id: 7,
            name: "Amala and Ewedu Soup",
            rating: "2.00",
            price: 2500,
            description: "A Yoruba dish consisting of smooth, brownish amala (yam flour) served with ewedu (jute leaf) soup.",
            image: "https://pbs.twimg.com/media/Ey9RpckWQAIzcXj.jpg",
            tag: "swallow",
        },
        {
            id: 8,
            name: "Dodo (Fried Plantains)",
            rating: "1.50",
            price: 500,
            description: "Sliced and fried ripe plantains, a popular side dish or snack.",
            image: "https://img-global.cpcdn.com/recipes/eb0e9da719bf6999/1200x630cq70/photo.jpg"
        },
        {
            id: 9,
            name: "Boli (Grilled Plantains)",
            rating: "5.00",
            price: 1000,
            description: "Ripe plantains grilled over an open flame until they are soft and slightly caramelized.",
            image: "https://guardian.ng/wp-content/uploads/2018/08/IMG_8068-1-e1534524746186.jpg"
        },
        {
            id: 10,
            name: "Fried Rice",
            rating: "6.50",
            price: 4400,
            description: "A colorful and flavorful rice dish cooked with vegetables, spices, and often with chicken or shrimp.",
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTaRy7YJ9hlRInUY1cRIkvxPZqIwGVQa-VCRg&usqp=CAU",
            tag: "rice",
        },
        {
            id: 11,
            name: "Fufu and Egusi Soup",
            rating: "4.00",
            price: 3000,
            description: "Fufu is a starchy side dish served with a thick, nutty Egusi soup.",
            image: "https://img-global.cpcdn.com/recipes/9cd060ad5ca13ba3/1200x630cq70/photo.jpg",
            tag: "swallow",
        },
        {
            id: 12,
            name: "Eba and Okra Soup",
            rating: "2.50",
            price: 3000,
            description: "Eba is made from cassava and served with okra soup, a slimy vegetable-based soup.",
            image: "https://www.allnigerianrecipes.com/bimages/okrasoup-patienceadah.jpg",
            tag: "swallow",
        },
        {
            id: 13,
            name: "Pepper Soup",
            rating: "3.75",
            price: 2500,
            description: "A spicy broth often made with assorted meats and fish, seasoned with hot peppers and aromatic spices.",
            image: "https://sisijemimah.com/wp-content/uploads/2016/11/Assorted-Meat-Pepper-Soup-1.jpg",
            tag: "Protein",
        },
        {
            id: 14,
            name: "Shawarma",
            rating: "5.50",
            price: "2,000",
            description: "A popular street food with Nigerian variations, typically consisting of seasoned meat (usually beef or chicken) wrapped in flatbread.",
            image: "https://cheflolaskitchen.com/wp-content/uploads/2018/07/Easy-Homemade-Chicken-Shawarma39.jpg"
        },
        {
            id: 15,
            name: "Ofada Rice and Ayamase Stew",
            rating: "3.00",
            price: 4000,
            description: "Ofada rice is a local variety served with Ayamase stew, a spicy pepper sauce.",
            image: "https://guardian.ng/wp-content/uploads/2019/07/ofada-rice-stew-e1563548726678.jpg",
            tag: "rice",
        },
        {
            id: 16,
            name: "Indomie Noodles",
            rating: "4.25",
            price: 1800,
            description: "Instant noodles cooked with a variety of spices and ingredients for a quick and tasty meal",
            image: "https://indomartz.com/cdn/shop/products/IndomieMiGorengFriedNoodlesOriginalFlavor2.webp?v=1675962648&width=1946"
        },
        {
            id: 17,
            name: "Yam Porridge",
            rating: "1.25",
            price: 3500,
            description: "Yam chunks cooked in a flavorful tomato and pepper sauce.",
            image: "https://www.thedreamafrica.com/wp-content/uploads/2018/01/Beef-Yam-Porridge.jpg"
        },
        {
            id: 18,
            name: "Chinchinga (Nigerian Kebabs)",
            rating: "2.75",
            price: 3100,
            description: "Skewered and grilled meat, often marinated in a spicy sauce.",
            image: "https://foodienotachef.com/wp-content/uploads/2021/06/new-SuyaSpiceChicken-2.png"
        },
        {
            id: 19,
            name: "Efo Riro",
            rating: "4.50",
            price: 5000,
            description: "A Yoruba vegetable soup made with assorted leafy greens, meat, and fish.",
            image: "https://lowcarbafrica.com/wp-content/uploads/2019/08/Efo-Riro-IG-2.jpg",
            tag: "soup",
        },
        {
            id: 20,
            name: "Banga Soup (Ofe Akwu)",
            rating: "1.75",
            price: 2200,
            description: "A palm nut soup often served with starchy sides like starch or pounded yam.",
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS1cSi0T2kvUuOiHVCLz2Reail1R0fiiLjStw&usqp=CAU",
            tag: "soup",
        },
        {
            id: 21,
            name: "Oha Soup",
            rating: "3.00",
            price: 3900,
            description: "A traditional Igbo soup made with oha leaves and flavored with spices and palm oil.",
            image: "https://i.ytimg.com/vi/egHS0xuyFws/maxresdefault.jpg",
            tag: "soup",
        },
        {
            id: 22,
            name: "Ogbolo Soup",
            rating: "4.00",
            price: 2000,
            description: "A delicious soup made from ogbolo seeds, vegetables, and spices.",
            image: "https://assets.unileversolutions.com/recipes-v2/159356.jpg",
            tag: "soup",
        },
        {
            id: 23,
            name: "Kilishi",
            rating: "5.50",
            price: 2000,
            description: "A Nigerian beef jerky, seasoned and dried to perfection, making it a popular snack.",
            image: "https://obalendefoods.com/cdn/shop/files/4F8230D4-C92C-4137-8F89-F26F48856F8F_1_201_a.jpg?v=1682913426&width=1445"
        },
        {
            id: 24,
            name: "Ukodo",
            rating: "2.50",
            price: 3300,
            description: "A yam pepper soup made with goat meat and yam chunks.",
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLHghu633m7tJEUQFr8t-FbmSN7qMdmjrbuQ&usqp=CAU"
        },
        {
            id: 25,
            name: "Tuwo Shinkafa",
            rating: "1.75",
            price: 3500,
            description: "A northern Nigerian dish made from mashed rice and served with various soups.",
            image: "https://eatwellabi.com/wp-content/uploads/2022/10/Jamaican-chicken-soup-and-tuwo-16-720x480.jpg",
            tag: "swallow",
        },
        {
            id: 26,
            name: "Afang Soup",
            rating: "2.00",
            price: 2000,
            description: "A vegetable soup made from the afang leaf, often cooked with a variety of proteins.",
            image: "https://agameals.com/wp-content/uploads/2022/11/maxresdefault-52-1140x694-1.jpg",
            tag: "soup",
        },
        {
            id: 27,
            name: "Abacha and Ugba",
            rating: "2.25",
            price: 3500,
            description: "A popular Igbo dish made from cassava and African oil bean seed.",
            image: "https://guardian.ng/wp-content/uploads/2018/08/Abacha.-Photo-Dailyfresheat-e1534627240972-1062x598.png"
        },
        {
            id: 28,
            name: "Semo and Egusi Soup",
            rating: "2.50",
            price: 3500,
            description: "Semo is a swallow made from semolina and is often served with egusi soup.",
            image: "https://amalacentralfoods.com/wp-content/uploads/2023/01/Egusi-soup.jpg",
            tag: "swallow",
        },
        {
            id: 29,
            name: "Gbegiri Soup",
            rating: "1.20",
            price: 2500,
            description: "A Yoruba bean soup typically served with amala.",
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR7D_90XpEYWI_Km6usKuijuJ-A2onIknM4WA&usqp=CAU",
            tag: "swallow",
        },
        {
            id: 30,
            name: "Akpu and Black Soup",
            rating: "3.00",
            price: 2900,
            description: "A traditional Igbo dish consisting of akpu (fermented cassava) and black soup.",
            image: "https://1.bp.blogspot.com/-ghuj6XkFp-w/X-soadJL7sI/AAAAAAAAATA/v6mbF4cbZwA_xtyB0aEki9jQQ9vAdyv7ACLcBGAsYHQ/w1200-h630-p-k-no-nu/0DD2AFAA-3233-4FB5-982B-91573C68B5ED.jpeg",
            tag: "swallow",
        },
        {
            id: 31,
            name: "Nkwobi",
            rating: "1.50",
            price: 4500,
            description: "A spicy cow foot dish often served as a side dish or appetizer.",
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTB0Er0CefZt6Dh1rFtp7n28z1GqIFcOFlnBQ&usqp=CAU"
        },
        {
            id: 32,
            name: "Asun",
            rating: "4.50",
            price: 3000,
            description: "Spicy grilled goat meat skewers, a popular Nigerian barbecue dish.",
            image: "https://guardian.ng/wp-content/uploads/2020/08/Peppered-Goat-Meat-Image-Youtube.jpg"
        },
        {
            id: 33,
            name: "Ekpang Nkukwo",
            rating: "3.75",
            price: 2300,
            description: "A Cross River State specialty made with cocoyam and leafy vegetables.",
            image: "https://comechopnaija.com/wp-content/uploads/2017/12/epkang.jpg"
        },
        {
            id: 34,
            name: "Pounded Yam and Ogbono Soup",
            rating: "5.00",
            price: 5500,
            description: "Pounded yam served with ogbono soup, a slimy Nigerian soup.",
            image: "https://aliyahsrecipesandtips.com/wp-content/uploads/2020/03/Ogbono-with-okra-soup-500x375.jpg",
            tag: "swallow",
        },
        {
            id: 35,
            name: "Ewa Agoyin",
            rating: "1.00",
            price: 2000,
            description: " Mashed beans served with a spicy sauce made from palm oil and ground peppers.",
            image: "https://www.bellanaija.com/wp-content/uploads/2023/08/1AAA64B1-448F-4F16-82B9-91A8DD8A1184.jpeg"
        },
        {
            id: 36,
            name: "Fried Fish",
            rating: "1.75",
            price: 2000,
            description: "Whole fish seasoned and deep-fried until crispy.",
            image: "https://images.squarespace-cdn.com/content/v1/52d3fafee4b03c7eaedee15f/1627342360931-9UPWBOPY8FL38EX45K2I/EOS+M50_4391.jpg"
        },
        {
            id: 37,
            name: "Starch and Banga Soup",
            rating: "2.25",
            price: 2500,
            description: "Starchy side dish served with banga soup made from palm fruit.",
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRSVhDmNdckyUaa0JBHzWd2L0FguPoH2EDDCA&usqp=CAU",
            tag: "soup",
        },
        {
            id: 38,
            name: "Ogi (Pap)",
            rating: "2.50",
            price: 1000,
            description: "A Nigerian breakfast porridge made from maize, millet, or sorghum.",
            image: "https://www.diettechafrica.com/wp-content/uploads/2020/07/Akamu-cover-pic.jpg"
        },
        {
            id: 39,
            name: "Boiled Maize and Pear",
            rating: "3.50",
            price: 3500,
            description: "Maize (corn) on the cob, boiled and often enjoyed with pear (avocado).",
            image: "https://i.ytimg.com/vi/BrbWbGwIh1I/maxresdefault.jpg"
        },
        {
            id: 40,
            name: "Garden Egg Sauce",
            rating: "4.00",
            price: 1000,
            description: "A tasty sauce made from garden eggs (a type of eggplant) and palm oil.",
            image: "https://morningfresh.com.ng/wp-content/uploads/2019/11/Untitled-1-1080x675.jpg"
        },
        {
            id: 41,
            name: "Spaghetti",
            rating: "2,500",
            price: 2500,
            description: "A unique Nigerian twist on the classic Italian pasta dish. It often includes a rich tomato-based sauce with spices and ingredients like vegetables, sausage, and sometimes a hint of local spices for a delightful fusion of flavors..",
            image: "https://i.ytimg.com/vi/xbVrrViGTJM/maxresdefault.jpg",
            tag: "rice",
        },
        {
            id: 42,
            name: "Ewedu and Starch",
            rating: "2,000",
            price: 4500,
            description: "A Yoruba dish with Ewedu soup, made from jute leaves, and served with starch.",
            image: "https://i.pinimg.com/736x/51/f6/10/51f61020e9e00fd823dee14c5fb79128.jpg"
        },
        {
            id: 43,
            name: "Ogbono and Semolina",
            rating: "800",
            price: 5000,
            description: " Ogbono soup served with semolina swallow.",
            image: "https://i.pinimg.com/originals/c8/8b/82/c88b82250db1219a309b9fdfb8b5d26e.jpg",
            tag: "swallow",
        },
        {
            id: 44,
            name: "Fisherman Soup",
            rating: "3.50",
            price: 4000,
            description: "A delicious soup made with various types of seafood, popular in the Niger Delta region.",
            image: "https://i.ytimg.com/vi/IivsmcVOC5o/maxresdefault.jpg",
            tag: "soup",
        },
        {
            id: 45,
            name: "Bitter Leaf Soup",
            rating: "2.50",
            price: 3200,
            description: "A traditional Nigerian soup made with bitter leaf and a variety of meats.",
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6JEtDt8o_is-LYuvoyl2r0Q1A_FQB26Sz0BiSSDBc2-1eAmlVR6rw0zjZFhgp3QpS__4&usqp=CAU",
            tag: "soup",
        },
        {
            id:46,
            name: "Edikang Ikong Soup",
            rating: "1.20",
            price: 3000,
            description: "A thick and creamy soup made with groundnuts (peanuts) and served with fufu.",
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSIWuJ4X8M0OkvTQuK39B6ihADM63uiJiQa8H8Uqx0ZUO-E5Jrt8LNjjP5lVDZYBDEJwKQ&usqp=CAU",
            tag: "soup",
        },
        {
            id: 47,
            name: "Groundnut Soup (Peanut Soup)",
            rating: "2.00",
            price: 2000,
            description: "A thick and creamy soup made with groundnuts (peanuts) and served with fufu.",
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJ4xirbmVaYfLLhjt7D9FWJyv2S6GrSJswlvcgq9pJDSJd2fh16gZohqgCfTH_os9i7xU&usqp=CAU",
            tag: "swallow",
        },
        {
            id: 48,
            name: "Fufu",
            rating: "1.50",
            price: 2500,
            description: "A staple Nigerian food made from starchy vegetables like cassava, yam, or plantains. It's boiled, pounded, and shaped into a dough-like consistency. Fufu is often served with a variety of delicious soups and sauces.",
            image: "https://recipefairy.com/wp-content/uploads/2021/06/how-to-make-fufu.jpg",
            tag: "swallow",
        },
        {
            id: 49,
            name: "Ugba Salad",
            rating: "5.00",
            price: 3500,
            description: "A salad made from African oil bean seed (ugba) and vegetables.",
            image: "https://www.shutterstock.com/image-photo/close-shot-plate-african-salad-600w-1529467949.jpg"
        },
        {
            id: 50,
            name: "Ofe Nsala (White Soup)",
            rating: "6.50",
            price: 3500,
            description: "A flavorful Igbo soup made with yam and a variety of proteins.",
            image: "https://i.ytimg.com/vi/tIjwSMTkRzI/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLC1jlc-wCG8uieQTi75xboEKMPe7Q",
            tag: "soup",
        },
        {
            id: 51,
            name: "Ewa Riro",
            rating: "1,500",
            price: 2100,
            description: " A delicious Yoruba dish made from mashed beans and a spicy sauce.",
            image: "https://cheflolaskitchen.com/wp-content/uploads/2017/01/ewa-riro-1.jpg",
            tag: "soup",
        },
        {
            id: 52,
            name: "Okpa",
            rating: "2,000",
            price: 2000,
            description: " A steamed bean pudding made from Bambara groundnuts, popular in the eastern part of Nigeria.",
            image: "https://tribuneonlineng.com/wp-content/uploads/2022/10/F4A5B55A-CF95-4BB5-BA44-E038ADCC73BF.jpeg"
        },
        {
            id: 53,
            name: "Achara Soup",
            rating: "800",
            price: 3500,
            description: "A sour soup made from cocoyam and flavored with achara (a type of vegetable).",
            image: "https://img-global.cpcdn.com/recipes/997f8d2bd854253b/1200x630cq70/photo.jpg",
            tag: "snacks",
        },
        {
            id: 54,
            name: "Kokoro",
            rating: "3.50",
            price: 1500,
            description: "A Nigerian snack made from roasted maize and sugar.",
            image: "https://3.bp.blogspot.com/-kqp2EAX51qo/UVJ5vORZvkI/AAAAAAAAAio/pT3zV0enliE/s1600/kokoro+nigerian+snacks.jpg"
        },
        {
            id: 55,
            name: "Ogiri",
            rating: "2.50",
            price: 3600,
            description: " A traditional Nigerian condiment made from fermented oil seeds.",
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSN6wALbctrv_WWOHWx3j8O43_Pb18clWUbGg&usqp=CAU"
        },
        {
            id:56,
            name: "Coconut Rice",
            rating: "1.20",
            price: 4000,
            description: "A flavorful rice dish cooked with coconut milk and spices.",
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTMZYkt1pYTNiUULIH4nwpKgMp-P5YyWYSgyg&usqp=CAU",
            tag: "rice",
        },
        {
            id: 57,
            name: "Nsala Soup",
            rating: "2.00",
            price: 3000,
            description: " A white soup made with yam and a blend of spices, popular in Igbo cuisine.",
            image: "https://i.ytimg.com/vi/yOr7sx6Usfg/maxresdefault.jpg",
            tag: "soup",
        },
        {
            id: 58,
            name: "Suya Spaghetti",
            rating: "1.50",
            price: 3800,
            description: " Spaghetti noodles with a spicy suya sauce, a fusion of Italian and Nigerian flavors.",
            image: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.facebook.com%2Fdeesdishes%2Fphotos%2Fa.161591282431675%2F219800876610715%2F%3Ftype%3D3&psig=AOvVaw023p2TXzEfqEDoZFb6obz3&ust=1697191922405000&source=images&cd=vfe&opi=89978449&ved=0CBEQjRxqFwoTCJjVmuWi8IEDFQAAAAAdAAAAABAJ"
        },
        {
            id: 59,
            name: "Gurasa",
            rating: "5.00",
            price: 2500,
            description: " A popular northern Nigerian bread, often served with sauce or grilled",
            image: "https://img-global.cpcdn.com/recipes/508f238f769dee1d/1200x630cq70/photo.jpg"
        },
        {
            id: 60,
            name: "Uji (Pap)",
            rating: "6.50",
            price: 3500,
            description: "A porridge made from fermented corn or millet, a common breakfast dish in Nigeria.",
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR2OpTdL5UpLNIcCtkGGuJmyF9sLLtyRU17QA&usqp=CAU"
        },
    ];
    
    function generateRandomRating() {
        return (Math.random() * (5 - 1) + 1).toFixed(2);
    }
    
    // Update the ratings for each food item in the array
    details.forEach((food) => {
        food.rating = generateRandomRating();
    });
    res.status(200).json(details)
    
}

module.exports = { apiFuction }